id: A388B6DE4
base_file: f144E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:46:44.921493
  last_modified_at: 2022-05-30 21:46:44.921501
