id: A388B6DE4
base_file: fFDB8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:46:44.924164
  last_modified_at: 2022-05-30 21:46:44.924167
